### ISSUE TITLE
Minor UI polishing

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#114]
Some minor polishing things:

- [x] change 'Login' to 'log in' on landing page (I tried to do this already but it got reverted somehow)
- [x] usually you have the 'confirm' button to the left of the cancel button, but on 'edit', it's the opposite. change 'Save' to left of cancel.
- [x] remove orphans from landing page. Maybe "Manage your sample metadata" and "Log in with your GitHub account to get started"

**Comment by nleroy917** [comment]
This is likely solved in the latest release

**Comment by nleroy917** [comment]
This is now available in the latest release (`0.7.x`)

**Comment by nsheff** [comment]
The orphans are still present (or are they just back again?) I'll create another issue for that again.

**Comment by nsheff** [comment]
Actually "log in" is back to "Login".

I'll just re-open this issue since 2 of the 3 things are still not fixed.

**Comment by nsheff** [comment]
- [x] I also see "Logout" instead of "Log out", can you also fix that?

**Comment by ayobi** [comment]
Spacing for log in, log out, and removal of orphans is now in release `0.9.x`
