### ISSUE TITLE
New columns with names, but no samples assigned values, are not saved

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#179]
Steps to reproduce:

1. Open a project edit page
2. Add a column to sample table. Don't add any values to any samples, just add the column.
3. Click save. Note "Successfully updated..." message.
4. Click back to a different page, and then re-open the project
5. Observe that your new column has disappeared. It was not saved.

**Comment by nleroy917** [comment]
I think this is addressed with the latest sample-table stability updates

**Comment by khoroshevskyi** [comment]
I was just checking this issue, and it seems that this issue is not solved

**Comment by nleroy917** [comment]
~~Not in production, but it should be locally if you have my changes~~

Nvm, it is still broken. Looks like it makes it to the server:
<img width="631" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/7b5ad74d-7e1c-4744-9847-1417ed28f322">

But we drop `na` values:
```python
sample_table_df = sample_table_df.dropna(axis=1, how="all")
sample_table_df.fillna("", inplace=True)
```

So, I gues this is unintended behavior? If we just remove this, does that have any unintended consequences?

**Comment by nleroy917** [comment]
Removing those `dropna` lines resolved the issue, but @khoroshevskyi I want to make sure that's ok and I won't be introducing other bugs if I do that

**Comment by nleroy917** [comment]
This was resolved with the `v0.9.x` release
